name    'mlog2waffle'
version '1.0'
source 'http://github.com/francetv/mlog2waffle.git'
author 'btl'
license 'Apache License, Version 2.0'
summary 'Download files with wget'
description 'A part of Wesh CLub'
project_page 'http://github.com/francetv/mlog2waffle.git'
